// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
using System.Buffers;

namespace BankApp
{
    class Program
    {
        public static void Main(string[] args)
        {
            var account = new BankAccount("Medal", 50000);
            Console.WriteLine($"Account {account.Number} was just created for {account.Owner} with {account.Balance}");

            account.MakeWithdrawal(320, DateTime.Now, "Food");
            Console.WriteLine(account.Balance);

        }





    }










}